### ISSUE TITLE
loading crash

### ISSUE THREAD

**Issue by spartaque12** [petrgeorgievsky/gtaRenderHook#11]
game doesnt loads, if it wasnt launched once to convert textures for gpu

specs: i7 2600k, rtx2060, 16 ram, win10x64 1909

to reproduce: install gta, install renderhook

latest build

**Comment by petrgeorgievsky** [comment]
Should be fixed with https://github.com/petrgeorgievsky/gtaRenderHook/commit/f6e8ddab930156a5b6b40172b3e32fa7a1fc84fb
